"""Tool schemas for the model-backed planner.

Explicit, not generated by reflection. This is the boundary where an untrusted
model's output becomes a structured request, so being able to read the exact
shape of every accepted input in one file is worth more than the convenience of
deriving it.

Every schema sets ``additionalProperties: false`` and lists ``required``, which
is what ``strict: true`` needs in order to guarantee the arguments validate.
"""

from __future__ import annotations

from typing import Any

__all__ = ["FINISH_TOOL", "operation_for_tool", "tool_definitions"]


def _tool(
    name: str, description: str, properties: dict[str, Any], required: list[str]
) -> dict[str, Any]:
    return {
        "name": name,
        "description": description,
        "input_schema": {
            "type": "object",
            "properties": properties,
            "required": required,
            "additionalProperties": False,
        },
        "strict": True,
    }


_PATH = {"type": "string", "description": "Absolute path. Must be within your scopes."}
_SHEET = {"type": "string", "description": "Sheet name. Omit for single-sheet files."}
_CELL = {"type": "string", "description": "A1-style cell reference, e.g. 'B14'."}

_SCHEMAS: dict[str, dict[str, Any]] = {
    "fs.read": _tool("fs_read", "Read a text file.", {"path": _PATH}, ["path"]),
    "fs.list": _tool("fs_list", "List the entries of a directory.", {"path": _PATH}, ["path"]),
    "fs.stat": _tool("fs_stat", "Read a path's size, mtime and kind.", {"path": _PATH}, ["path"]),
    "fs.write": _tool(
        "fs_write",
        "Write a text file, replacing its contents. Reversible.",
        {"path": _PATH, "content": {"type": "string"}},
        ["path", "content"],
    ),
    "fs.append": _tool(
        "fs_append",
        "Append text to a file. Reversible.",
        {"path": _PATH, "content": {"type": "string"}},
        ["path", "content"],
    ),
    "fs.copy": _tool(
        "fs_copy",
        "Copy a file. Needs read on the source and write on the destination.",
        {"source": _PATH, "path": _PATH},
        ["source", "path"],
    ),
    "fs.move": _tool(
        "fs_move",
        "Move a file. Needs delete on the source and write on the destination.",
        {"source": _PATH, "path": _PATH},
        ["source", "path"],
    ),
    "fs.mkdir": _tool(
        "fs_mkdir",
        "Create a directory. Compensable: undone by deleting it.",
        {"path": _PATH},
        ["path"],
    ),
    "fs.delete": _tool(
        "fs_delete",
        "Delete a file or empty directory. Reversible: the checkpoint holds the bytes.",
        {"path": _PATH},
        ["path"],
    ),
    "sheet.list": _tool("sheet_list", "List the sheets in a workbook.", {"path": _PATH}, ["path"]),
    "sheet.read_cell": _tool(
        "sheet_read_cell",
        "Read one cell from a workbook.",
        {"path": _PATH, "sheet": _SHEET, "cell": _CELL},
        ["path", "cell"],
    ),
    "sheet.read_range": _tool(
        "sheet_read_range",
        "Read a rectangular range from a workbook.",
        {
            "path": _PATH,
            "sheet": _SHEET,
            "start": {"type": "string", "description": "Top-left cell, e.g. 'A1'."},
            "end": {"type": "string", "description": "Bottom-right cell. Omit for all."},
        },
        ["path", "start"],
    ),
    "sheet.find_row": _tool(
        "sheet_find_row",
        "Find the 1-indexed row where a column holds a value.",
        {
            "path": _PATH,
            "sheet": _SHEET,
            "column": {"type": "string", "description": "Column letter, e.g. 'A'."},
            "value": {"type": "string"},
        },
        ["path", "column", "value"],
    ),
    "sheet.set_cell": _tool(
        "sheet_set_cell",
        "Set one cell in a workbook. Reversible, and verified by reading it back.",
        {"path": _PATH, "sheet": _SHEET, "cell": _CELL, "value": {"type": "string"}},
        ["path", "cell", "value"],
    ),
    "app.open": _tool(
        "app_open",
        (
            "Open a file in the system's default application -- an image in the "
            "image viewer, a PDF in the PDF reader. Use this when the user asks "
            "to see, view, show, display or open something."
        ),
        {"path": _PATH},
        ["path"],
    ),
    "code.run": _tool(
        "code_run",
        (
            "Write and run Python in a sandbox. Use this whenever there is no "
            "typed tool for the job -- converting between file formats, parsing, "
            "reshaping data, bulk renaming, anything computational. This is "
            "almost always better than giving up or clicking. "
            "The script starts in a workspace containing 'materials/' (read-only "
            "copies of the files you listed) and 'out/' (already created). "
            "Write results to 'out/'; only files there can be saved afterwards "
            "with code_materialize. Nothing you write elsewhere reaches the "
            "user's machine. "
            "There is NO network access. Only the Python standard library and "
            "the preinstalled packages are importable."
        ),
        {
            "code": {
                "type": "string",
                "description": "Python source. Write output files into 'out/'.",
            },
            "materials": {
                "type": "array",
                "items": {"type": "string"},
                "description": (
                    "Absolute paths to copy into 'materials/'. Must be within your fs.read scopes."
                ),
            },
        },
        ["code", "materials"],
    ),
    "code.materialize": _tool(
        "code_materialize",
        (
            "Save a file the sandbox produced onto the real filesystem. This is "
            "the only way sandbox output reaches the user, and it is an ordinary "
            "write: it is checkpointed, verified and undoable. "
            "'artifact' MUST be one of the names listed under 'artifacts' in the "
            "code_run result you just received. Do not invent a name. 'path' MUST "
            "be a full absolute path including the filename, inside your scopes."
        ),
        {
            # No concrete example here on purpose: a small model copies whatever
            # example it is shown, and a plausible-looking filename it never
            # produced is worse than a missing argument -- the broker denies it
            # and the model has no idea why.
            "artifact": {
                "type": "string",
                "description": "A name from the 'artifacts' list in the code_run result.",
            },
            "path": {
                "type": "string",
                "description": (
                    "Absolute destination path, including the filename. Must be within your scopes."
                ),
            },
        },
        ["artifact", "path"],
    ),
    "ui.click": _tool(
        "ui_click",
        (
            "Click a control in the focused window. Prefer naming the control "
            "with 'element' -- clicking by coordinate breaks whenever the window "
            "moves, resizes or the display scaling differs, and it fails "
            "silently by landing on whatever is there instead. Give x and y only "
            "when the control has no accessible name."
        ),
        {
            "element": {
                "type": "string",
                "description": "The control's visible name, e.g. 'Save'.",
            },
            "x": {"type": "integer", "description": "Screen x. Only without 'element'."},
            "y": {"type": "integer", "description": "Screen y. Only without 'element'."},
            "button": {"type": "string", "description": "left, right or middle. Default left."},
            "window": {
                "type": "string",
                "description": (
                    "Title of the window to act in. It is brought to the front "
                    "first, and nothing is sent if it cannot be."
                ),
            },
        },
        [],
    ),
    "ui.type": _tool(
        "ui_type",
        "Type text into a window, at wherever its keyboard focus is. Click the field first.",
        {
            "text": {"type": "string"},
            "window": {
                "type": "string",
                "description": (
                    "Title of the window to act in. It is brought to the front "
                    "first, and nothing is sent if it cannot be."
                ),
            },
        },
        ["text"],
    ),
    "ui.key": _tool(
        "ui_key",
        "Press a key chord in a window, e.g. 'ctrl+s' or 'alt+f4'.",
        {
            "chord": {"type": "string"},
            "window": {
                "type": "string",
                "description": (
                    "Title of the window to act in. It is brought to the front "
                    "first, and nothing is sent if it cannot be."
                ),
            },
        },
        ["chord"],
    ),
    "ui.screenshot": _tool(
        "ui_screenshot",
        (
            "List a window's title and the names of its visible controls -- call "
            "this before clicking, to learn what the controls are called. This is "
            "the weakest evidence the runtime has: it says something rendered, "
            "not that anything is true. Never treat it as confirmation."
        ),
        {
            "window": {
                "type": "string",
                "description": (
                    "Title of the window to act in. It is brought to the front "
                    "first, and nothing is sent if it cannot be."
                ),
            },
        },
        [],
    ),
    "memory.recall": _tool(
        "memory_recall",
        (
            "Resolve a vague reference to a real path -- 'the excel from "
            "yesterday', 'the budget spreadsheet'. Returns the path, whether it "
            "is confident, and why. Use this instead of guessing a filename. "
            "If confident is false, ask the user rather than picking."
        ),
        {"phrase": {"type": "string", "description": "What the user called it."}},
        ["phrase"],
    ),
    "memory.recent": _tool(
        "memory_recent",
        "List files this runtime recently changed, most recent first.",
        {"limit": {"type": "integer", "description": "Max results. Default 10."}},
        [],
    ),
    "proc.spawn": _tool(
        "proc_spawn",
        (
            "Run an external program. Always irreversible and always requires human "
            "approval, because this runtime cannot observe what a subprocess did. "
            "Prefer a typed tool when one exists."
        ),
        {
            "command": {"type": "string"},
            "args": {"type": "array", "items": {"type": "string"}},
        },
        ["command"],
    ),
}

FINISH_TOOL = _tool(
    "finish",
    "Call when the goal is met, or when you cannot proceed. Ends the run.",
    {
        "summary": {"type": "string", "description": "What was done, or why not."},
        "succeeded": {"type": "boolean"},
    },
    ["summary", "succeeded"],
)

# Tool names cannot contain dots, so they are the operation with dots replaced.
_TOOL_TO_OPERATION = {schema["name"]: op for op, schema in _SCHEMAS.items()}


def tool_definitions(operations: tuple[str, ...]) -> list[dict[str, Any]]:
    """Schemas for the operations actually available, plus ``finish``.

    Offering a tool the router cannot serve wastes a turn and teaches the model
    a capability it does not have, so the caller passes only what its adapters
    support.
    """
    tools = [_SCHEMAS[op] for op in operations if op in _SCHEMAS]
    return [*(_with_live_detail(tool) for tool in tools), FINISH_TOOL]


def _with_live_detail(tool: dict[str, Any]) -> dict[str, Any]:
    """Append facts that are only knowable at runtime.

    The sandbox's package roster is the motivating case. A model told nothing
    will assume ``requests`` exists and write a script that fails; a model told
    ``pypdf`` is present writes a better one. That belongs in the description
    the model actually reads, not in a README.
    """
    if tool["name"] != "code_run":
        return tool

    from ..sandbox import describe_for_planner

    detail = describe_for_planner()
    return {**tool, "description": f"{tool['description']}\n{detail}"}


def operation_for_tool(tool_name: str) -> str | None:
    return _TOOL_TO_OPERATION.get(tool_name)
